base/urls.py
#
from django.urls import (include, path)

from . import views

app_name = 'base'

urlpatterns = [
    path('',
         views.home,
         name="home"
         ),
    path('update-metadata/<int:pk>',
         views.UpdateMetadataView.as_view(),
         name="update_metadata"
         ),
    path('accounts/',
         include('django.contrib.auth.urls')
         ),
]

covid_ht/urls.py
from django.contrib import admin
from django.urls import (include, path)
from django.utils import timezone
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog

from base.urls import urlpatterns as base_urls
from data.urls import urlpatterns as data_urls
from units.urls import urlpatterns_units as units_urls

from .urls_api_v1 import urlpatterns as urlpatterns_api_v1


def get_version():
    return timezone.now().timestamp()


urlpatterns = [
    path(
        'jsi18n/',
        cache_page(86400, key_prefix='js18n-%s' % get_version())(
            JavaScriptCatalog.as_view()
        ),
        name='javascript-catalog'
    ),
    path('admin/', admin.site.urls),
    path('django-ai/',
         include('django_ai.ai_base.urls')),
    #
    path('api/auth/',
         include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/', include((urlpatterns_api_v1, "rest-api"))),
    #
    path('data/', include((data_urls, "data"))),
    path('units/', include((units_urls, "units"))),
    path('', include((base_urls, "base"))),
]

data/urls.py
#
from django.urls import path

from . import views

app_name = 'data'

urlpatterns = [
    path('input',
         views.input,
         name="input"
         ),
    path('csv',
         views.CSV().as_view(),
         name="csv"
         ),
    path('<str:uuid>/edit',
         views.edit,
         name="edit"
         ),
    path('<str:uuid>',
         views.detail,
         name="detail"
         ),
    path('',
         views.public_list,
         name="public-list"
         ),
]

data/models.py
import uuid

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import (MaxValueValidator, MinValueValidator, )
from django.db import models
from django.utils.timezone import now
from django.utils.translation import gettext_lazy as _
from django.urls import reverse

from .mixins import ConversionFieldsModelMixin


class Data(ConversionFieldsModelMixin, models.Model):
    """
    Main Data object: Metadata, Auxiliary and Clinical Results (Main)
    """
    MAIN_FIELDS = {
        'rbc': {'unit': 'x1012L', },
        'wbc': {'unit': 'x109L', },
        'hgb': {'unit': 'gL', },
        'hgbp': {'unit': 'mgdL', },
        'hgbg': {'unit': 'percentage', },
        'htg': {'unit': 'gL', },
        'hct': {'unit': 'gL', },
        'mcv': {'unit': 'fL', },
        'mch': {'unit': 'pgcell', },
        'mchc': {'unit': 'gL', },
        'rdw': {'unit': 'percentage', },
        'rtc': {'unit': 'x109L', },
        'plt': {'unit': 'x109L', },
        'mpv': {'unit': 'fL', },
        'pt': {'unit': 's', },
        'inr': {'unit': None, },
        'aptt': {'unit': 's', },
        'tct': {'unit': 's', },
        'fbg': {'unit': 'gL', },
        'atb': {'unit': 'kUIL', },
        'bt': {'unit': 'minutes', },
        'vsy': {'unit': 'cP', },
        'esr': {'unit': 'mmH', },
        'crp': {'unit': 'mgL', },
        'aat': {'unit': 'mgL', },
        'pct': {'unit': 'mgL', },
        'neut': {'unit': 'x109L'},
        'nbf': {'unit': 'x109L'},
        'lymp': {'unit': 'x109L'},
        'mono': {'unit': 'x109L'},
        'mnl': {'unit': 'x109L'},
        'cd4': {'unit': 'x109L'},
        'eo': {'unit': 'x109L'},
        'baso': {'unit': 'x109L'},
        'iga': {'unit': 'x109L'},
        'igd': {'unit': 'x109L'},
        'ige': {'unit': 'x109L'},
        'igg': {'unit': 'x109L'},
        'igm': {'unit': 'x109L'}
    }

    AUXILIARY_FIELDS = [
        'age', 'sex', 'is_diabetic', 'is_hypertense', 'is_overweight',
        'is_at_altitude', 'is_with_other_conds',
    ]
    CHTUID_FIELD = ['chtuid'] if settings.CHTUID_USE_IN_CLASSIFICATION else []

    LEARNING_FIELDS_CATEGORICAL = CHTUID_FIELD + [
        'sex', 'is_diabetic', 'is_hypertense', 'is_overweight',
        'is_at_altitude', 'is_with_other_conds',
    ]
    LEARNING_LABELS = 'is_covid19'
    LEARNING_FIELDS_MONOTONIC_CONSTRAINTS = "None"
    # conversion_function = unit_conversion

    SEX_CHOICES = (
        (None, _("Not Available")),
        (False, _("Female")),
        (True, _("Male"))
    )

    # METADATA FIELDS
    chtuid = models.CharField(
        _("Covid-HT Unique IDentifier"),
        max_length=5, blank=True,
        default=settings.CHTUID
    )
    unit = models.ForeignKey(
        "units.Unit",
        on_delete=models.PROTECT,
        verbose_name=_("Unit"),
        related_name='data'
    )
    user = models.ForeignKey(
        "base.User",
        on_delete=models.PROTECT,
        verbose_name=_("User"),
        related_name='data'
    )
    is_finished = models.BooleanField(
        _("Is Finished?"),
        default=False,
        help_text=_(
            'Is the record finished or complete? All data has been recorded '
            'and the internal identifier has been removed.'
        )
    )
    unit_ii = models.CharField(
        _("Unit Internal Identifier"),
        max_length=50,
        blank=True, null=True,
        help_text=_('Unit Internal Identifier for mapping to physical record'),
    )
    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=True
    )
    timestamp = models.DateTimeField(
        _("Timestamp"),
        default=now
    )
    # -> CLASSIFICATION FIELDS
    # LABELS
    is_covid19 = models.BooleanField(
        _("Is COVID19?"),
        blank=True, null=True
    )
    # AUXILIARY FIELDS
    age = models.PositiveSmallIntegerField(
        _("Age"),
        blank=True, null=True
    )
    sex = models.BooleanField(
        _("Sex"),
        choices=SEX_CHOICES,
        blank=True, null=True
    )
    is_diabetic = models.BooleanField(
        _("Is Diabetic?"),
        null=True
    )
    is_hypertense = models.BooleanField(
        _("Is Hypertense?"),
        null=True
    )
    is_overweight = models.BooleanField(
        _("Is Overweight Patient?"),
        null=True
    )
    is_at_altitude = models.BooleanField(
        _("Is at Altitude?"),
        null=True,
        help_text=_('Is the Patient at High Altitude (> 1500m)'),
    )
    is_with_other_conds = models.BooleanField(
        _("Is with other Relevant Conditions?"),
        null=True,
        help_text=_('Is the Patient with other Relevant Conditions? '
                    '(Transplantation, Blood disorders, etc.)'),
    )
    # MAIN FIELDS
    # Red Blood Cells
    rbc = models.DecimalField(
        _("RBC (x10^12/L)"),
        max_digits=5, decimal_places=3,
        blank=True, null=True,
        help_text=_('Red Blood Cells (x10^12/L or mlm/mm^3)'),
        validators=[MinValueValidator(2.0), MaxValueValidator(8.0)]
    )
    hgb = models.SmallIntegerField(
        _("HGB (g/L)"),
        blank=True, null=True,
        help_text=_('Hemoglobin (g/L)'),
        validators=[MinValueValidator(50), MaxValueValidator(250)]
    )
    hgb_UmmolL = models.DecimalField(
        _("HGB (mmol/L)"),
        max_digits=4, decimal_places=3,
        blank=True, null=True,
        help_text=_('Hemoglobin (mmol/L)'),
        validators=[MinValueValidator(0.5), MaxValueValidator(4)]
    )
    hgbp = models.SmallIntegerField(
        _("HGBP (mg/dL)"),
        blank=True, null=True,
        help_text=_('Hemoglobin in Plasma (mg/dL)'),
        validators=[MinValueValidator(0.1), MaxValueValidator(8)]
    )
    hgbp_UumolL = models.DecimalField(
        _("HGBP (umol/L)"),
        max_digits=3, decimal_places=2,
        blank=True, null=True,
        help_text=_('Hemoglobin in Plasma (umol/L)'),
        validators=[MinValueValidator(0.1), MaxValueValidator(2)]
    )
    hgbg = models.DecimalField(
        _("Glycated Hemoglobin (% of HGB)"),
        max_digits=4, decimal_places=2,
        blank=True, null=True,
        help_text=_('Glycated Hemoglobin (% of Hemoglobin)'),
        validators=[MinValueValidator(1), MaxValueValidator(8)]
    )
    htg = models.DecimalField(
        _("HTG (g/L)"),
        max_digits=4, decimal_places=3,
        blank=True, null=True,
        help_text=_('Haptoglobin (g/L)'),
        validators=[MinValueValidator(0.1), MaxValueValidator(5)]
    )
    hct = models.DecimalField(
        _("HCT (L/L)"),
        max_digits=3, decimal_places=2,
        blank=True, null=True,
        help_text=_('Hematocrit (g/L)'),
        validators=[MinValueValidator(0.1), MaxValueValidator(1)]
    )
    mcv = models.SmallIntegerField(
        _("MCV (fL)"),
        blank=True, null=True,
        help_text=_('Mean Cell Volume (fL)'),
        validators=[MinValueValidator(50), MaxValueValidator(150)]
    )
    mch = models.SmallIntegerField(
        _("MCH (pg/cell)"),
        blank=True, null=True,
        help_text=_('Mean Cell Hemoglobin (pg/cell)'),
        validators=[MinValueValidator(10), MaxValueValidator(50)]
    )
    mch_Ufmolcell = models.SmallIntegerField(
        _("MCH (fmol/cell)"),
        blank=True, null=True,
        help_text=_('Mean Cell Hemoglobin (fmol/cell)'),
        validators=[MinValueValidator(0.1), MaxValueValidator(2)]
    )
    mchc = models.SmallIntegerField(
        _("MCHC (g/L)"),
        blank=True, null=True,
        help_text=_('Mean Corpuscular Hemoglobin Concentration (g/L)'),
        validators=[MinValueValidator(2), MaxValueValidator(5)]
    )
    mchc_UgdL = models.SmallIntegerField(
        _("MCHC (g/dL)"),
        blank=True, null=True,
        help_text=_('Mean Corpuscular Hemoglobin Concentration (g/dL)'),
        validators=[MinValueValidator(20), MaxValueValidator(50)]
    )
    mchc_UmmolL = models.SmallIntegerField(
        _("MCHC (mmol/L)"),
        blank=True, null=True,
        help_text=_('Mean Corpuscular Hemoglobin Concentration (mmol/L)'),
        validators=[MinValueValidator(2), MaxValueValidator(8)]
    )
    rdw = models.DecimalField(
        _("RDW (%)"),
        max_digits=4, decimal_places=2,
        blank=True, null=True,
        help_text=_('Red Blood Cell Distribution Width (%)'),
        validators=[MinValueValidator(5.0), MaxValueValidator(30.0)]
    )
    rtc = models.DecimalField(
        _("Reticulocytes (x10^9/L)"),
        blank=True, null=True,
        max_digits=4, decimal_places=2,
        help_text=_('Reticulocytes (x10^9/L)'),
        validators=[MinValueValidator(5.0), MaxValueValidator(250.0)]
    )
    rtc_Upercentage_Rrbc = models.DecimalField(
        _("RTC (% of RBC)"),
        max_digits=4, decimal_places=2,
        blank=True, null=True,
        help_text=_('Reticulocytes (% of RBC)'),
        validators=[MinValueValidator(0), MaxValueValidator(50.0)]
    )
    # Coagulation
    plt = models.SmallIntegerField(
        _("PLT (x10^9/L)"),
        blank=True, null=True,
        help_text=_('Platelets (x10^9/L or x1000/uL)'),
        validators=[MinValueValidator(50), MaxValueValidator(1000)]
    )
    mpv = models.DecimalField(
        _("MPV (fL)"),
        max_digits=4, decimal_places=2,
        blank=True, null=True,
        help_text=_('Mean Platelet Volume (fL)'),
        validators=[MinValueValidator(1), MaxValueValidator(50)]
    )
    pt = models.DecimalField(
        _("PT (s)"),
        max_digits=4, decimal_places=2,
        blank=True, null=True,
        help_text=_('Prothrombin Time (s)'),
        validators=[MinValueValidator(50), MaxValueValidator(550)]
    )
    inr = models.DecimalField(
        _("INR"),
        max_digits=3, decimal_places=2,
        blank=True, null=True,
        help_text=_('International Normalized Ratio'),
        validators=[MinValueValidator(0.1), MaxValueValidator(3)]
    )
    aptt = models.SmallIntegerField(
        _("APTT (s)"),

data/v1/views.py
from django.conf import settings
from django.http import Http404

from rest_framework import generics
from rest_framework import status
from rest_framework.pagination import PageNumberPagination
from rest_framework.permissions import BasePermission, SAFE_METHODS
from rest_framework.request import clone_request
from rest_framework.response import Response

from ..models import Data
from ..serializers import (DataInputSerializer, DataListSerializer, )


class StandardResultsSetPagination(PageNumberPagination):
    page_size = 25
    page_size_query_param = 'page_size'
    max_page_size = 10000


class IsOwnerOrReadOnly(BasePermission):
    # https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions
    def has_object_permission(self, request, view, obj):
        if request.method in SAFE_METHODS:
            return True
        return obj.user == request.user


class DataPrivacyMode(BasePermission):
    """
    Restricts safe methods for not authenticated users on DATA_PRIVACY_MODE
    and always require authentication for not safe ones.
    """
    def has_permission(self, request, view):
        if request.method in SAFE_METHODS:
            return (
                not settings.DATA_PRIVACY_MODE or request.user.is_authenticated
            )
        return request.user.is_authenticated


class NetworkPUTAsCreateMixin(object):
    """
    The following mixin class supports PUT-as-create for data sharing between
    covid-ht nodes. Data is propagated through the nodes by PUT requests, which
    creates or updates the records and ignores the request if the chtuid is the
    same as the current node.
    (from https://gist.github.com/tomchristie/a2ace4577eff2c603b1b)
    """
    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object_or_none()
        serializer = self.get_serializer(
            instance, data=request.data, partial=partial
        )
        serializer.is_valid(raise_exception=True)

        if instance is None:
            self.perform_create(serializer)
            return Response(serializer.data, status=status.HTTP_201_CREATED)

        if self.perform_update(serializer):
            return Response(serializer.data)
        else:
            return Response(status=status.HTTP_208_ALREADY_REPORTED)

    def partial_update(self, request, *args, **kwargs):
        kwargs['partial'] = True
        return self.update(request, *args, **kwargs)

    def get_object_or_none(self):
        try:
            return self.get_object()
        except Http404:
            if self.request.method == 'PUT':
                # For PUT-as-create operation, we need to ensure that we have
                # relevant permissions, as if this was a POST request.  This
                # will either raise a PermissionDenied exception, or simply
                # return None.
                self.check_permissions(clone_request(self.request, 'POST'))
            else:
                # PATCH requests where the object does not exist should still
                # return a 404 response.
                raise

    def get_object(self):
        queryset = self.get_queryset()
        filter = {
            self.lookup_field: self.request.data.get(self.lookup_field, None)
        }
        obj = generics.get_object_or_404(queryset, **filter)
        self.check_object_permissions(self.request, obj)
        return obj


class DataListCreateUpdate(
        NetworkPUTAsCreateMixin, generics.UpdateAPIView,
        generics.ListCreateAPIView):
    queryset = Data.objects.all()
    serializer_class = DataInputSerializer
    pagination_class = StandardResultsSetPagination
    permission_classes = [DataPrivacyMode, ]
    lookup_field = 'uuid'

    def perform_create(self, serializer):
        serializer.save(
            user=self.request.user,
            unit=self.request.user.unit
        )

    def perform_update(self, serializer):
        if not serializer.validated_data['chtuid'] == settings.CHTUID:
            serializer.save(
                user=self.request.user,
                unit=self.request.user.unit
            )
            return True
        return False

    def list(self, request):
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = DataListSerializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = DataListSerializer(queryset, many=True)
        return Response(serializer.data)

    def paginate_queryset(self, queryset):
        if self.paginator and \
                self.request.query_params.get(
                    self.paginator.page_query_param, None) == 'no':
            return None
        return super().paginate_queryset(queryset)


class DataReadUpdate(generics.RetrieveUpdateAPIView):
    queryset = Data.objects.all()
    serializer_class = DataInputSerializer
    lookup_field = 'uuid'
    permission_classes = [DataPrivacyMode, IsOwnerOrReadOnly]

data/templates/data/detail.html
{% extends "base/base.html" %}
{% load i18n materializecss data_tags %}


{% block content %}

	<h1>{% translate "Data Detail" %}</h1>

	<h5>{{ data.unit.id }} - {{ data.unit.name }}</h5>

	<h5>{{ data.uuid }}</h5>

	<h5>{{ data.timestamp }}</h5>

	<br>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'is_covid19' %}</strong>
		</div>
		<div class="col s8">
			{{ data.is_covid19|yesno|upper }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'age' %}</strong>
		</div>
		<div class="col s8">
			{{ data.age }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'sex' %}</strong>
		</div>
		<div class="col s8">
			{{ data.get_sex_display }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'is_diabetic' %}</strong>
		</div>
		<div class="col s8">
			{{ data.is_diabetic|yesno:_("yes,no,not available")|title }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'is_hypertense' %}</strong>
		</div>
		<div class="col s8">
			{{ data.is_hypertense|yesno:_("yes,no,not available")|title }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'is_overweight' %}</strong>
		</div>
		<div class="col s8">
			{{ data.is_overweight|yesno:_("yes,no,not available")|title }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'is_at_altitude' %}</strong>
		</div>
		<div class="col s8">
			{{ data.is_at_altitude|yesno:_("yes,no,not available")|title }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'is_with_other_conds' %}</strong>
		</div>
		<div class="col s8">
			{{ data.is_with_other_conds|yesno:_("yes,no,not available")|title }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'rbc' %}</strong>
		</div>
		<div class="col s8">
			{{ data.rbc }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'wbc' %}</strong>
		</div>
		<div class="col s8">
			{{ data.wbc }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'hgb' %}</strong>
		</div>
		<div class="col s8">
			{{ data.hgb }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'hct' %}</strong>
		</div>
		<div class="col s8">
			{{ data.hct }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'mcv' %}</strong>
		</div>
		<div class="col s8">
			{{ data.mcv }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'mch' %}</strong>
		</div>
		<div class="col s8">
			{{ data.mch }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'mchc' %}</strong>
		</div>
		<div class="col s8">
			{{ data.mchc }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'rdw' %}</strong>
		</div>
		<div class="col s8">
			{{ data.rdw }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'plt' %}</strong>
		</div>
		<div class="col s8">
			{{ data.plt }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'neut' %}</strong>
		</div>
		<div class="col s8">
			{{ data.neut }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'lymp' %}</strong>
		</div>
		<div class="col s8">
			{{ data.lymp }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'mono' %}</strong>
		</div>
		<div class="col s8">
			{{ data.mono }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'eo' %}</strong>
		</div>
		<div class="col s8">
			{{ data.eo }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'baso' %}</strong>
		</div>
		<div class="col s8">
			{{ data.baso }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'iga' %}</strong>
		</div>
		<div class="col s8">
			{{ data.iga }}
		</div>
	</div>

	<div class="row">
		<div class="col s4 right-align">
			<strong>{% get_verbose_field_name data 'igm' %}</strong>
		</div>
		<div class="col s8">
			{{ data.igm }}
		</div>
	</div>

	{% if request.user == data.user %}
	<div class="row">
		<div class="col s4 right-align">
			&nbsp;
		</div>
		<div class="col s8">
			<a class="btn" href="{% url "data:edit" data.uuid %}">
                  <i class="material-icons">edit</i>
           	</a>
		</div>
	</div>
	{% endif %}

{% endblock content %}

data/templates/data/edit.html
{% extends "base/base.html" %}
{% load i18n materializecss %}


{% block content %}

	<h1>{% translate "Edit Data" %}</h1>

	<h5>uuid: {{ data.uuid }}</h5>

	<div class="row">
		<div class="col">
			<form action="" method="post">
				{% csrf_token %}
				{% if dataform.errors %}
					<p class="errorlist">{% translate "Errors prevented saving the data, check below:" %}</p>
				{% endif %}

				{% include "data/form_input.html" with dataform=dataform %}

				<div class="row">
					<input type="submit" name="_save" value="{% translate 'Save' %}" class="btn right blue lighten-2">
					<a href="{% url 'units:current:data' %}" class="btn red left">Cancel</a>
				</div>
			</form>
		</div>
	</div>

{% endblock content %}

data/templates/data/form_classify.html
{% load i18n materializecss %}

	{% if dataform.non_field_errors %}
    <blockquote>
        {% for non_field_error in dataform.non_field_errors %}
             {{ non_field_error }}
        {% endfor %}
    </blockquote>
	{% endif %}

	{% include "data/form_common.html" with dataform=dataform %}

data/templates/data/form_common.html
{% load i18n materializecss data_tags %}

	{% for group_field in dataform.get_grouped_fields %}
		<div class="row">
			{% for field in group_field %}
				<div class="col s{{ group_field|col_size }}">
					{{ dataform|get_field:field|materializecss}}
				</div>
			{% endfor %}
	</div>
	{% endfor %}

data/templates/data/form_input.html
{% load i18n materializecss %}

	{% if dataform.non_field_errors %}
    <blockquote>
        {% for non_field_error in dataform.non_field_errors %}
             {{ non_field_error }}
        {% endfor %}
    </blockquote>
	{% endif %}

	{% include "data/form_common.html" with dataform=dataform %}

data/templates/data/input.html
{% extends "base/base.html" %}
{% load i18n materializecss %}


{% block content %}

	{% if not request.user.unit %}

		<h4>{% translate "A unit must be selected for a User in order to input data." %}</h4>

	{% else %}

		<h4>
			{{ request.user.unit }}
		</h4>

		<h1>{% translate "Data Input" %}</h1>

		<div class="row">
			<div class="col">
				<form action="" method="post">
					{% csrf_token %}

					{% if dataform.errors %}
					<p class="errorlist">{% translate "Errors detected in the submitted data, check below:" %}</p>
					{% endif %}

					{% include "data/form_input.html" with dataform=dataform %}

					<div class="row">
						<input type="submit" name="_addanother" value="{% translate 'Save and Add Another' %}" class="btn right blue darken-2">
						<input type="submit" name="_save" value="{% translate 'Save' %}" class="btn right blue lighten-2">
						<a href="{% url 'units:current:data' %}" class="btn red left">Cancel</a>
					</div>
				</form>
			</div>
		</div>

	{% endif %}
{% endblock content %}

{% block extra_js %}
	<script type="text/javascript">

	(function($) {

    	unit_ii = $("input[name$='unit_ii']")
    	unit_ii.focus()


	})(django.jQuery);

	</script>
{% endblock extra_js %}

data/templates/data/public_list.html
{% extends "base/base.html" %}
{% load i18n data_tags %}

{% block content %}
    <div class="row">
        <div class="col s12 m8">
           <h1>Data</h1>
        </div>
        {% if data %}
        <div class="col s12 m4">
            <p>
              <b>{% translate "Dataset Size" %}</b>: {{ rows }} &times; {{ cols }}<br>
              <b>{% translate "Last Updated" %}</b>: {{ last_updated }}<br>
            </p>
            <p><a href="{% url 'data:csv' %}" class="btn btn-large green darken-3"><i class="material-icons left">download</i>{% translate ".CSV" %}</a></p>
        </div>
        {% endif %}
    </div>

  {% if data %}
	<table class="responsive-table">

        <thead>
          <tr>
              <th>{% translate "Unit" %}</th>
              <th>uuid</th>
            {% for field in fields %}
            	<th>
            		{% translate field.verbose_name %}
            	</th>
            {% endfor %}
          </tr>
        </thead>

        <tbody>
          {% for row in data %}
          <tr>
              <td>{{ row.unit.id }}</td>
              <td><a href="{% url 'data:detail' uuid=row.uuid %}">{{ row.uuid }}</a></td>
          	{% for field in fields %}
          		<td>{% get_row_field row field %}</td>
          	{% endfor %}
          </tr>
          {% endfor %}
        </tbody>

    </table>

    {% include "base/includes/paginator.html" with page_obj=data view="data:public-list" %}
  {% else %}
  <p>{% translate "No data available." %}</p>
  {% endif %}
{% endblock content %}