base/urls.py
#
from django.urls import (include, path)

from . import views

app_name = 'base'

urlpatterns = [
    path('',
         views.home,
         name="home"
         ),
    path('update-metadata/<int:pk>',
         views.UpdateMetadataView.as_view(),
         name="update_metadata"
         ),
    path('accounts/',
         include('django.contrib.auth.urls')
         ),
]

covid_ht/urls.py
from django.contrib import admin
from django.urls import (include, path)
from django.utils import timezone
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog

from base.urls import urlpatterns as base_urls
from data.urls import urlpatterns as data_urls
from units.urls import urlpatterns_units as units_urls

from .urls_api_v1 import urlpatterns as urlpatterns_api_v1


def get_version():
    return timezone.now().timestamp()


urlpatterns = [
    path(
        'jsi18n/',
        cache_page(86400, key_prefix='js18n-%s' % get_version())(
            JavaScriptCatalog.as_view()
        ),
        name='javascript-catalog'
    ),
    path('admin/', admin.site.urls),
    path('django-ai/',
         include('django_ai.ai_base.urls')),
    #
    path('api/auth/',
         include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/', include((urlpatterns_api_v1, "rest-api"))),
    #
    path('data/', include((data_urls, "data"))),
    path('units/', include((units_urls, "units"))),
    path('', include((base_urls, "base"))),
]

data/urls.py
#
from django.urls import path

from . import views

app_name = 'data'

urlpatterns = [
    path('input',
         views.input,
         name="input"
         ),
    path('csv',
         views.CSV().as_view(),
         name="csv"
         ),
    path('<str:uuid>/edit',
         views.edit,
         name="edit"
         ),
    path('<str:uuid>',
         views.detail,
         name="detail"
         ),
    path('',
         views.public_list,
         name="public-list"
         ),
]

units/urls.py
#
from django.urls import (include, path)

from . import views

app_name = 'units'

urlpatterns_unit = [
    path('users',
         views.unit_users_list,
         name="users-list"
         ),
    path('users/new',
         views.unit_users_new,
         name="users-new"
         ),
    path('users/<int:pk>',
         views.unit_users_detail,
         name="users-detail"
         ),
    path('users/<int:pk>/edit',
         views.unit_users_edit,
         name="users-edit"
         ),
    path('users/<int:pk>/set-password',
         views.unit_users_set_password,
         name="users-set-password"
         ),
    path('edit',
         views.unit_edit,
         name="edit"
         ),
    path('data',
         views.unit_data,
         name="data"
         ),
    path('data/csv',
         views.CSV().as_view(),
         name="data-csv"
         ),
    path('',
         views.unit_dashboard,
         name="dashboard"
         ),
]

urlpatterns_units = [
    path('current/', include((urlpatterns_unit, "current"))),
    path('<int:pk>',
         views.detail,
         name="detail"
         ),
    path('',
         views.list,
         name="list"
         ),
]

base/v1/views.py
from django.conf import settings
from django.utils.translation import gettext_lazy as _

from rest_framework import generics
from rest_framework.response import Response
from rest_framework import status

from data.serializers import (
    DataClassificationSerializer, DatasetClassificationSerializer
)
from data.models import Data

from ..models import CurrentClassifier


class Classify(generics.GenericAPIView):
    """
    Endpoint for classifying data (single observation).
    """
    serializer_class = DataClassificationSerializer
    use_network = False
    graph = False
    _classifier = None

    def get_data(self, serializer):
        data = Data.apply_conversion_fields_rules_to_dict(
            serializer.validated_data
        )
        return data

    def get_classifier(self):
        if not self._classifier:
            self._classifier = CurrentClassifier.get()
        return self._classifier

    def predict(self, data):
        if self.use_network:
            return self.get_classifier().network_predict(data)
        else:
            return self.get_classifier().predict(data) + (None, )

    def generate_graph(self, data):
        if settings.GRAPHING:
            return self.get_classifier().generate_graph(data)
        return None

    def post(self, request, format=None):
        """
        Return the result of classification if data submitted is valid.
        """
        self.use_network = \
            self.request.GET.get('use_network', False) in ["True", "true"]
        self.graph = \
            self.request.GET.get('graph', False) in ["True", "true"]
        if self.get_classifier():
            serializer = self.serializer_class(data=request.data)
            if serializer.is_valid():
                (result, result_prob, votes) = \
                    self.predict(self.get_data(serializer))
                response_content = {'result': result, 'prob': result_prob}
                if self.use_network:
                    response_content['votes'] = votes
                if self.graph:
                    response_content['graph'] = \
                        self.generate_graph(self.get_data(serializer))
                return Response(response_content, status=status.HTTP_200_OK)
            else:
                return Response(
                    serializer.errors,
                    status=status.HTTP_400_BAD_REQUEST
                )
        return Response(
                    {'detail': _("Classification Unavailable")},
                    status=status.HTTP_503_SERVICE_UNAVAILABLE
                )

    def get(self, request, format=None):
        if self.get_classifier():
            metadata = self.get_classifier().get_local_classifier().metadata
            metadata["chtuid"] = settings.CHTUID
            return Response(metadata, status=status.HTTP_200_OK)
        return Response(
                    {'detail': _("Classification Unavailable")},
                    status=status.HTTP_503_SERVICE_UNAVAILABLE
                )


class ClassifyDataset(Classify):
    """
    Endpoint for classifying datasets (multiple observations).
    """
    serializer_class = DatasetClassificationSerializer

    def get_data(self, serializer):
        data = []
        for s_vd in serializer.validated_data['dataset']:
            d = Data.apply_conversion_fields_rules_to_dict(s_vd)
            data.append(d)
        return data

base/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
# from django.contrib.contenttypes.models import ContentType
from django.shortcuts import get_object_or_404, render
from django.views.generic import RedirectView
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe

from data.forms import DataClassificationForm
from data.models import Data

from .models import CurrentClassifier, ExternalClassifier, NetworkNode


def home(request):
    classifier = CurrentClassifier.get()
    nodes = NetworkNode.objects.filter(classification_request=True)
    example_data = getattr(settings, "EXAMPLE_DATA_V2", False)
    chtuid = getattr(settings, "CHTUID", "-")
    graphing = getattr(settings, "GRAPHING", False)
    (result, result_prob, votes, classifier_error, graph) = \
        None, None, None, None, None
    if request.method == 'POST':
        dataform = DataClassificationForm(request.POST)
        if dataform.is_valid():
            data = Data.apply_conversion_fields_rules_to_dict(
                dataform.cleaned_data
            )
            try:
                (result, result_prob, votes) = classifier.network_predict(data)
                result = result[0]
                result_prob = result_prob[0]
                if graphing:
                    graph = mark_safe(classifier.generate_graph(data)[0])
            except Exception as e:
                classifier_error = str(e)
    else:
        dataform = DataClassificationForm()

    return render(
        request,
        'base/home.html',
        {
            'classifier': classifier,
            'nodes': nodes,
            'classifier_error': classifier_error,
            'example_data': example_data,
            'chtuid': chtuid,
            'dataform': dataform,
            'result': result,
            'result_prob': result_prob,
            'votes': votes,
            'graph': graph
        }
    )


class UpdateMetadataView(UserPassesTestMixin, RedirectView):
    """
    Updates metadata for External Classifiers
    """
    permanent = False

    def test_func(self):
        return self.request.user.is_superuser or self.request.user.is_staff

    def get_redirect_url(self, *args, **kwargs):
        ec = get_object_or_404(ExternalClassifier, pk=kwargs['pk'])
        updated = ec.update_metadata()
        if updated:
            messages.success(self.request,
                             _("Success at updating metadata"))
        else:
            messages.error(self.request,
                           _("Errors ocurred while updating metadata, check "
                             "network error logs"))
        return self.request.META.get('HTTP_REFERER', '/')

base/templates/base/includes/footer.html
{% load static i18n %}

<div class="container">
    <div class="row" style="padding-bottom: 10px;">

        <div class="col m4 l4 s12">
          <a href="/"><h5 class="brand-logo footer-title white-text">covid-ht</h5></a>
        </div>

        <div class="col m8 l8 s12 right-align">
          {% if request.user.pk %}
            <h6 class="footer-title white-text">{{ request.user.name }}<br>{{ request.user.unit }}</h6>
          {% else %}
            <a href="{% url 'base:login' %}" class="btn blue">
              <i class="material-icons white-text small right">login</i>
              {% trans "Login" %}
            </a>
          {% endif %}
          <a href="#" class="btn btn-floating grey">
              <i class="material-icons white-text small">keyboard_arrow_up</i>
          </a>
        </div>

    </div>
</div>

base/templates/base/includes/head.html
{% load static %}

<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>
        {% block title %}
            {% block title_prefix %}
                covid-ht
            {% endblock %}
            {% comment %}
            {% if self.seo_title %}
                {{ self.seo_title }}
            {% else %}
                {{ self.title }}
            {% endif %}
            {% endcomment %}
        {% endblock %}
    </title>

    <meta name="description" content="{% if self.search_description %}{{ self.search_description }}{% endif %}">

    <!-- Materialize CSS -->
    <!--
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/material-icons.css' %}">
    <!-- Compiled and minified CSS -->
    <!--
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/materialize.css' %}">

    <!-- Theme CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/covid-ht.css' %}">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <link rel="shortcut icon" href="{%  static 'img/favicon.ico' %}">

    <!-- Javascript catalog -->
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>

    {% block head_extra %}
    {% endblock head_extra %}

    <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

base/templates/base/includes/header.html
{% load static i18n %}

<div class="nav-wrapper">
  <nav class="" role="navigation">
    <div class="nav-wrapper container">

      {% if request.user.pk %}
        <a href="#" data-target="nav-mobile" class="sidenav-trigger show-on-large"><i class="material-icons">menu</i></a>

        <ul class="left">
          <li>
            <a href="{% url 'base:home' %}">
              <i class="material-icons text-darken-4 orange-text small">my_location</i>
            </a>
          </li>
          <li>
            <a href="{% url 'units:current:dashboard' %}">
              <i class="material-icons text-darken-4 orange-text small">dashboard</i>
            </a>
          </li>
          <li>
            <a href="{% url 'data:input' %}">
              <i class="material-icons text-darken-4 orange-text small">keyboard</i>
            </a>
          </li>
        </ul>
      {% endif %}

      <ul class="left">
          {% if not request.user.pk %}
          <li>
            <a href="https://covid-ht.readthedocs.io/en/latest/about.html">{% trans "About" %}</a>
          </li>

          <li>
            <a href="{% url 'units:list' %}">{% trans "Units" %}</a>
          </li>

          <li>
            <a href="{% url 'data:public-list' %}">{% trans "Data" %}</a>
          </li>
          {% endif %}
      </ul>

      <a id="logo-container" href="/" class="brand-logo right show-on-small"><span class="brand-logo-short"></span> covid-ht</a>

    </div>

  </nav>
</div>

  {% if request.user.pk %}
  <ul id="nav-mobile" class="sidenav">

    <li class="center">
      <div class="user-view" >
        <div class="background">
          <!-- <img src="images/office.jpg"> -->
        </div>
        <a href="{% url 'units:current:users-detail' request.user.pk %}">
          {% if request.user.image %}
          <img class="circle" src="{{ request.user.image }}">
          {% else %}
          <i class="material-icons large">person</i>
          {% endif %}
        </a>
        {% if request.user.unit %}
          <a href="{% url 'units:current:users-detail' request.user.pk %}"><span class="white-text name">{{ request.user.name }}</span></a>
          <a href="{% url 'units:current:dashboard' %}"><span class="white-text">{{ request.user.unit }}</span></a>
         {% else %}
          <span class="white-text name">{{ request.user.name }}</span>
        {% endif %}
        </div>
    </li>

    <li>
      <a href="{% url 'base:home' %}">
        <i class="material-icons text-darken-4 orange-text small">my_location</i>
        {% trans "Classify" %}
      </a>
    <li>

    <li>
      <a href="{% url 'units:current:dashboard' %}">
        <i class="material-icons text-darken-4 orange-text small">dashboard</i>
        {% trans "Your Unit" %}
      </a>
    </li>

  {% comment %}
    <li>
      <a href="{% url 'units:current:users-list' %}">
        <i class="material-icons text-darken-4 orange-text small">people</i>
        {% trans "Unit's Members" %}
      </a>
    </li>

    <li>
      <a href="{% url 'units:current:data' %}">
        <i class="material-icons text-darken-4 orange-text small">data</i>
        {% trans "Unit's Data" %}
      </a>
    </li>
  {% endcomment %}

    <li>
      <a href="{% url 'data:input' %}">
        <i class="material-icons text-darken-4 orange-text small">keyboard</i>
        {% trans "Data Input" %}
      </a>
    </li>

    <li>
      <a href="{% url 'units:list' %}">{% trans "Units" %}</a>
    <li>

    <li>
      <a href="{% url 'data:public-list' %}">{% trans "Data" %}</a>
    <li>

    <li>
      <a href="https://covid-ht.readthedocs.io/en/latest/about.html">{% trans "About" %}</a>
    <li>

    <li>
      <a href="{% url 'base:logout' %}">
        <i class="material-icons text-darken-4 orange-text small">logout</i>
        {% trans "Logout" %}
      </a>
    </li>

    <li><a class="sidenav-close" href="#!"><i class="material-icons right">close</i></a></li>
  </ul>
  {% endif %}

base/templates/base/includes/messages.html
{% if messages %}
    <div role="alertdialog">
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %} role="alert">{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

base/templates/base/includes/paginator.html
{% load i18n %}

<ul class="pagination paginator-style">
    {% if page_obj.has_previous %}
        <li class="waves-effect">
            <a href="{% url view %}?page={{ page_obj.previous_page_number }}">
                <i class="material-icons">chevron_left</i>
            </a>
        </li>
        <li class="paginator-label waves-effect">
            <a href="{% url view %}?page={{ page_obj.previous_page_number }}">
                {% translate "Previous" %}
            </a>
        </li>
    {% endif %}

    {% if page_obj.paginator.num_pages > 1 %}
        <li class="paginator-label">
          <a href="#">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</a>
        </li>
    {% endif %}

    {% if page_obj.has_next %}
        {% if page_obj.has_previous %}
            <li><i class="material-icons grey-text text-lighten-3 paginator-sep">more_vert</i></li>
        {% endif %}

        <li class="paginator-label waves-effect">
            <a href="{% url view %}?page={{ page_obj.next_page_number }}">
            {% translate "Next" %}
            </a>
        </li>
        <li class="waves-effect">
            <a href="{% url view %}?page={{ page_obj.next_page_number }}">
            <i class="material-icons">chevron_right</i>
            </a>
        </li>
    {% endif %}
</ul>

base/templates/base/includes/submit_button.html
{% load i18n %}

<p class="center">
	<button class="btn waves-effect waves-light blue darken-3" type="submit" name="action">
		{% if not label %}
		{% translate "Submit" %}
		{% else %}
		{% translate label %}
		{% endif %}
	   	<i class="material-icons right">{{ icon }}</i>
	</button>
</p>