base/urls.py
#
from django.urls import (include, path)

from . import views

app_name = 'base'

urlpatterns = [
    path('',
         views.home,
         name="home"
         ),
    path('update-metadata/<int:pk>',
         views.UpdateMetadataView.as_view(),
         name="update_metadata"
         ),
    path('accounts/',
         include('django.contrib.auth.urls')
         ),
]

covid_ht/urls.py
from django.contrib import admin
from django.urls import (include, path)
from django.utils import timezone
from django.views.decorators.cache import cache_page
from django.views.i18n import JavaScriptCatalog

from base.urls import urlpatterns as base_urls
from data.urls import urlpatterns as data_urls
from units.urls import urlpatterns_units as units_urls

from .urls_api_v1 import urlpatterns as urlpatterns_api_v1


def get_version():
    return timezone.now().timestamp()


urlpatterns = [
    path(
        'jsi18n/',
        cache_page(86400, key_prefix='js18n-%s' % get_version())(
            JavaScriptCatalog.as_view()
        ),
        name='javascript-catalog'
    ),
    path('admin/', admin.site.urls),
    path('django-ai/',
         include('django_ai.ai_base.urls')),
    #
    path('api/auth/',
         include('rest_framework.urls', namespace='rest_framework')),
    path('api/v1/', include((urlpatterns_api_v1, "rest-api"))),
    #
    path('data/', include((data_urls, "data"))),
    path('units/', include((units_urls, "units"))),
    path('', include((base_urls, "base"))),
]

data/urls.py
#
from django.urls import path

from . import views

app_name = 'data'

urlpatterns = [
    path('input',
         views.input,
         name="input"
         ),
    path('csv',
         views.CSV().as_view(),
         name="csv"
         ),
    path('<str:uuid>/edit',
         views.edit,
         name="edit"
         ),
    path('<str:uuid>',
         views.detail,
         name="detail"
         ),
    path('',
         views.public_list,
         name="public-list"
         ),
]

units/urls.py
#
from django.urls import (include, path)

from . import views

app_name = 'units'

urlpatterns_unit = [
    path('users',
         views.unit_users_list,
         name="users-list"
         ),
    path('users/new',
         views.unit_users_new,
         name="users-new"
         ),
    path('users/<int:pk>',
         views.unit_users_detail,
         name="users-detail"
         ),
    path('users/<int:pk>/edit',
         views.unit_users_edit,
         name="users-edit"
         ),
    path('users/<int:pk>/set-password',
         views.unit_users_set_password,
         name="users-set-password"
         ),
    path('edit',
         views.unit_edit,
         name="edit"
         ),
    path('data',
         views.unit_data,
         name="data"
         ),
    path('data/csv',
         views.CSV().as_view(),
         name="data-csv"
         ),
    path('',
         views.unit_dashboard,
         name="dashboard"
         ),
]

urlpatterns_units = [
    path('current/', include((urlpatterns_unit, "current"))),
    path('<int:pk>',
         views.detail,
         name="detail"
         ),
    path('',
         views.list,
         name="list"
         ),
]

base/models.py
from itertools import combinations
from numpy import mean
from numpy import nan as np_nan
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import requests
from scipy.special import comb
from sklearn import metrics as sklearn_metrics
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import OrdinalEncoder
from tempfile import TemporaryFile

from django.db import models
from django.db.models.signals import post_save
from django.core.cache import cache
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from django_ai.supervised_learning.models import HGBTreeClassifier, SVC
from rest_framework import status

from data.models import Data
from data.serializers import DataClassificationSerializer, DataShareSerializer


matplotlib.use('agg')


class User(AbstractUser):
    """
    Custom User Model for covid-ht
    """
    MANAGER = 0
    DATA = 1

    USER_TYPE_CHOICES = (
        (MANAGER, _("Manager of Unit")),
        (DATA, _("Data Input")),
    )

    user_type = models.PositiveSmallIntegerField(
        _("User Type"),
        choices=USER_TYPE_CHOICES, default=DATA
    )
    unit = models.ForeignKey(
        "units.Unit",
        on_delete=models.PROTECT,
        verbose_name=_("Unit"),
        blank=True, null=True,
        related_name='users'
    )
    cellphone = models.CharField(
        _("Cellphone"),
        max_length=50,
        blank=True, null=True,
    )

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

    def url(self):
        return(reverse('units:current:users-detail', args=[self.pk]))

    @property
    def name(self):
        return "{0} {1}".format(
            self.first_name.upper(), self.last_name.upper()
        )

    @property
    def is_manager(self):
        return (self.user_type == self.MANAGER) \
            or self.is_superuser or self.is_staff

    def save(self, *args, **kwargs):
        self.first_name = self.first_name.upper()
        self.last_name = self.last_name.upper()
        super().save(*args, **kwargs)


class CurrentClassifierManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()\
            .select_related('classifier', 'external')


class CurrentClassifier(models.Model):
    """
    Singleton Model for selecting which classifier should be used
    """
    NETWORK_VOTING_DISABLED = 0
    NETWORK_VOTING_MAJORITY = 1
    NETWORK_VOTING_MIN_POSITIVE = 2
    NETWORK_VOTING_MIN_NEGATIVE = 3

    BTP_LOCAL = 0
    BTP_SCORES = 1

    NETWORK_VOTING_CHOICES = (
        (NETWORK_VOTING_DISABLED, _("No Network Voting")),
        (NETWORK_VOTING_MAJORITY, _("Majority")),
        (NETWORK_VOTING_MIN_POSITIVE, _("Minimum of Positives")),
        (NETWORK_VOTING_MIN_NEGATIVE, _("Minimum of Negatives")),
    )

    BTP_CHOICES = (
        (BTP_LOCAL, _("Prefer Local Vote")),
        (BTP_SCORES, _("Prefer Highest Score")),
    )

    classifier = models.OneToOneField(
        'supervised_learning.SupervisedLearningTechnique',
        on_delete=models.PROTECT,
        related_name='current_classifier',
        verbose_name=_("Internal Classifier"),
        blank=True, null=True
    )
    external = models.OneToOneField(
        'base.ExternalClassifier',
        on_delete=models.PROTECT,
        related_name='current_classifier',
        verbose_name=_("External Classifier"),
        blank=True, null=True
    )
    network_voting = models.PositiveSmallIntegerField(
        _("Network Voting Policy"),
        choices=NETWORK_VOTING_CHOICES, default=NETWORK_VOTING_DISABLED
    )
    breaking_ties_policy = models.PositiveSmallIntegerField(
        _("Breaking Ties Policy"),
        choices=BTP_CHOICES, default=BTP_LOCAL,
        help_text=_(
            "Only applicable for Majority voting policy."
        )
    )
    network_voting_threshold = models.PositiveSmallIntegerField(
        _("Network Voting Threshold"),
        blank=True, null=True,
        help_text=_(
            "Only applicable for Minimum Positives / Negatives voting "
            "policies."
        )
    )

    objects = CurrentClassifierManager()

    class Meta:
        verbose_name = _("Current Classifier")

    def __str__(self):
        return str(self.classifier)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.update_cache()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        cache.set("CurrentClassifier", None)

    @classmethod
    def get(cls):
        return cache.get('CurrentClassifier', CurrentClassifier.set())

    @classmethod
    def set(cls, instance=None):
        if instance is None:
            last_instance = CurrentClassifier.objects.last()
            if not last_instance:
                cache.set('CurrentClassifier', None)
                return None
            else:
                instance = last_instance
        # Trigger fk queries and property loading
        local_classifier = instance.get_local_classifier()
        if not hasattr(local_classifier, 'service_url'):
            local_classifier.get_engine_object()
        #
        cache.set('CurrentClassifier', instance)
        return instance

    def update_cache(self):
        CurrentClassifier.set(instance=self)

    def get_local_classifier(self):
        if self.external:
            return self.external
        else:
            return self.classifier._get_technique()

    def predict(self, observations):
        local_classifier = self.get_local_classifier()
        if not isinstance(observations, list):
            observations = [observations]
        if local_classifier.is_inferred:
            if hasattr(local_classifier, 'service_url'):
                result = local_classifier.predict(observations)
                return (result['result'], result['prob'])
            else:
                (res, scores) = \
                    local_classifier.predict(observations, include_scores=True)
                results = ["POSITIVE" if r else "NEGATIVE" for r in res]
                return (results, scores)
        return (None, None)

    def network_predict(self, observations, include_votes=True):
        if not isinstance(observations, list):
            observations = [observations]
        votes = self._get_network_votes(observations)
        if len(votes) > 1:
            results_list, scores_list = [], []
            for idx in range(0, len(observations)):
                votes_positive = [
                    node for node in votes
                    if votes[node]["result"] and
                    votes[node]["result"][idx] == "POSITIVE"
                ]
                votes_negative = [
                    node for node in votes
                    if votes[node]["result"] and
                    votes[node]["result"][idx] == "NEGATIVE"
                ]
                scores_positive = [
                    votes[node]["prob"][idx] for node in votes
                    if node in votes_positive
                ]
                scores_negative = [
                    votes[node]["prob"][idx] for node in votes
                    if node in votes_negative
                ]
                if self.network_voting == self.NETWORK_VOTING_MAJORITY:
                    if len(votes_positive) > len(votes_negative):
                        result = ("POSITIVE", mean(scores_positive))
                    elif len(votes_positive) < len(votes_negative):
                        result = ("NEGATIVE", mean(scores_negative))
                    else:
                        if self.breaking_ties_policy == self.BTP_LOCAL:
                            if "local" in votes_positive:
                                result = ("POSITIVE", mean(scores_positive))
                            else:
                                result = ("NEGATIVE", mean(scores_negative))
                        else:  # self.breaking_ties_policy == self.BTP_SCORE
                            if mean(scores_positive) > mean(scores_negative):
                                result = ("POSITIVE", mean(scores_positive))
                            else:
                                result = ("NEGATIVE", mean(scores_negative))
                elif self.network_voting == self.NETWORK_VOTING_MIN_NEGATIVE:
                    if len(votes_negative) >= self.network_voting_threshold:
                        result = ("NEGATIVE", mean(scores_negative))
                    else:
                        result = ("POSITIVE", mean(scores_positive))
                else:  # self.net_voting == self.NETWORK_VOTING_MIN_POSITIVE:
                    if len(votes_positive) >= self.network_voting_threshold:
                        result = ("POSITIVE", mean(scores_positive))
                    else:
                        result = ("NEGATIVE", mean(scores_negative))
                results_list.append(result[0])
                scores_list.append(result[1])
        else:
            only_vote = list(votes.items())[0]
            results_list = only_vote[1]["result"]
            scores_list = only_vote[1]["prob"]
        if include_votes:
            return (results_list, scores_list, votes)
        else:
            return (results_list, scores_list)

    def generate_graph(self, observations):
        technique = self.classifier._get_technique()
        if not isinstance(observations, list):
            observations = [observations]
        graphs = [
            technique.generate_graph(observation)
            for observation in observations
        ]
        return graphs

    def _get_network_votes(self, observations):
        votes = {}

data/views.py
#
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.conf import settings
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import Http404
from django.shortcuts import (get_object_or_404, redirect, render, )
from django.utils import timezone
from django.utils.decorators import method_decorator
# from django.utils.translation import gettext_lazy as _
from rest_framework import generics

from .forms import (DataInputForm, )
from .models import Data
from .renderers import PublicCSVRenderer
from .serializers import PublicDataSerializer
from .v1.views import DataPrivacyMode


def is_not_allowed_in_data_privacy_mode(function):
    actual_decorator = user_passes_test(
        lambda u:
        False if settings.DATA_PRIVACY_MODE and u.is_anonymous else True
    )
    if function:
        return actual_decorator(function)
    return actual_decorator  # pragma: no cover


@is_not_allowed_in_data_privacy_mode
def public_list(request):
    page = request.GET.get('page', 1)
    data_qs = Data.objects.filter(is_finished=True).order_by("-timestamp")

    # Pagination
    paginator = Paginator(data_qs, 50)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:  # pragma: no cover
        data = paginator.page(1)
    except EmptyPage:  # pragma: no cover
        data = paginator.page(paginator.num_pages)

    fields_all = list(Data._meta.fields)
    fields_excluded = [
        'id', 'user_id', 'unit_ii', 'timestamp', 'unit', 'uuid',
    ]
    fields = [
        field for field in fields_all if field.attname not in fields_excluded
    ]
    rows = data_qs.count()
    cols = len(fields)
    if rows:
        last_updated = Data.objects.last().timestamp
    else:
        last_updated = None
    return render(
        request,
        'data/public_list.html',
        {
            'data': data,
            'fields': fields,
            'rows': rows,
            'cols': cols,
            'last_updated': last_updated
        }
    )


class CSV(generics.ListAPIView):
    renderer_classes = (PublicCSVRenderer, )
    serializer_class = PublicDataSerializer
    queryset = Data.objects.filter(is_finished=True)
    permission_classes = [DataPrivacyMode, ]

    def finalize_response(self, request, response, *args, **kwargs):
        response['Content-Disposition'] = \
            "attachment; filename=covid-ht-data-{0}UTC.csv".format(
                timezone.now().utcnow().strftime("%Y%m%dT%I%M")
            )
        return super().finalize_response(request, response, *args, **kwargs)


@is_not_allowed_in_data_privacy_mode
def detail(request, uuid):
    data = get_object_or_404(Data, uuid=uuid)
    return render(
        request,
        'data/detail.html',
        {
            'data': data,
        }
    )


@login_required
def edit(request, uuid):
    data = get_object_or_404(Data, uuid=uuid)
    if not request.user == data.user:
        raise Http404()
    if request.method == 'POST':
        dataform = DataInputForm(request.POST, instance=data)
        if dataform.is_valid():
            data = dataform.save(commit=False)
            data.timestamp = timezone.now()
            data.save()
            return redirect("units:current:data")
    else:
        dataform = DataInputForm(instance=data)

    return render(
        request,
        'data/edit.html',
        {
            'data': data,
            'dataform': dataform,
        }
    )


@login_required
def input(request):
    if request.method == 'POST':
        dataform = DataInputForm(request.POST)
        if dataform.is_valid():
            data = dataform.save(commit=False)
            data.user = request.user
            data.unit = request.user.unit
            data.save()
            if '_addanother' in dataform.data:
                return redirect("data:input")
            else:
                return redirect("units:current:data")
    else:
        dataform = DataInputForm()

    return render(
        request,
        'data/input.html',
        {
            'dataform': dataform,
        }
    )

units/templates/units/dashboard.html
{% extends "base/base.html" %}

{% load i18n %}

{% block content %}
	<h2>
		<i class="material-icons circle text-darken-4 orange-text icon-primary">dashboard</i>
		{% if not unit %}
			{% translate "No Unit has been selected" %}
			{% else %}
			{{ unit.name }} {% translate "Dashboard" %}
		{% endif %}
	</h2>

	<p>{% translate "Timezone" %}: {{ unit.timezone }} </p>

	<div class="row">
		<div class="col s12 m6">
			<h4>{% translate "Members" %}</h4>

			<p><b>{% translate "Managers" %}</b>: {{ members_m_size }} </p>

            <p><b>{% translate "Data Input" %}</b>: {{ members_di_size }}</p>

			<p>
				<a href="{% url 'units:current:users-list' %}" class="btn waves-effect waves-light blue darken-3">
					<i class="material-icons right">people</i>
					{% translate "Members" %}
				</a>
			</p>
		</div>

		<div class="col s12 m6">
			<h4>{% translate "Data" %}</h4>

			<p><b>{% translate "Dataset Size" %}</b>: {{ data_size }} </p>

            <p><b>{% translate "Last Updated" %}</b>: {{ data_last_updated }}</p>

			<p>
				<a href="{% url 'units:current:data' %}" class="btn waves-effect waves-light green darken-3">
					<i class="material-icons right">people</i>
					{% translate "Unit's Data" %}
				</a>
			</p>
		</div>
	</div>

    {% if request.user.is_manager %}

    <div class="fixed-action-btn">
	  <a class="btn-floating btn-large red">
	    <i class="large material-icons">more_horiz</i>
	  </a>
	  <ul>
	    <li><a href="{% url 'units:current:edit' %}" class="btn-floating blue darken-1">
	    	<i class="material-icons">mode_edit</i></a>
	    </li>
	  </ul>
	</div>

    {% endif %}

{% endblock content %}

{% block extra_js %}
	{% if request.user.is_manager %}
	<script>
	  document.addEventListener('DOMContentLoaded', function() {
	    var elems = document.querySelectorAll('.fixed-action-btn');
	    var instances = M.FloatingActionButton.init(elems, {
	      direction: 'left'
	    });
	  });
	</script>
	{% endif %}
{% endblock extra_js %}

units/templates/units/data.html
{% extends "base/base.html" %}
{% load i18n data_tags %}

{% block content %}
    <div class="row">
        <div class="col s12 m8">
           <h1>Unit's Data</h1>
           <h3>{{ request.user.unit }}</h3>
        </div>
        <div class="col s12 m4">
            <p>
              <b>{% translate "Dataset Size" %}</b>: {{ rows }} &times; {{ cols }}<br>
              <b>{% translate "Last Updated" %}</b>: {{ last_updated }}<br>
            </p>
            <p><a href="{% url 'units:current:data-csv' %}" class="btn btn-large green darken-3"><i class="material-icons left">download</i>{% translate ".CSV" %}</a></p>
        </div>
    </div>

  {% if data %}
	<table class="responsive-table">

        <thead>
          <tr>
              <th>User</th>
            {% for field in fields %}
            	<th>
            		{% translate field.verbose_name %}
            	</th>
            {% endfor %}
              <th></th>
          </tr>
        </thead>

        <tbody>
          {% for row in data %}
          <tr>
              <td>{{ row.user.name }}</td>
          	{% for field in fields %}
          		<td>{% get_row_field row field %}</td>
          	{% endfor %}
              <td>{% if row.user == request.user %}
                <a href="{% url "data:edit" row.uuid %}">
                  <i class="material-icons">edit</i>
                </a>
              {% endif %}</td>
          </tr>
          {% endfor %}
        </tbody>

    </table>

    {% include "base/includes/paginator.html" with page_obj=data view="units:current:data" %}
    {% else %}
    <p>{% translate "No data available." %}</p>
    {% endif %}

{% endblock content %}

units/templates/units/detail.html
{% extends "base/base.html" %}

{% load i18n %}

{% block content %}
	<h2>
		<i class="material-icons circle text-darken-4 orange-text icon-primary">home</i>
		{{ unit.name }}
	</h2>

	<h4 class="cellphone-number blue-grey-text text-darken-2 indent-small">
    	<i class="material-icons prefix" style="vertical-align: bottom;">chevron_right</i>
    	{{ unit.description }}
    </h4>

    <p>{% translate "Timezone" %}: {{ unit.timezone }} </p>

	<div class="row">
		<div class="col s12 m6">
			<h4>{% translate "Members" %}</h4>

			<p><b>{% translate "Managers" %}</b>: {{ members_m_size }} </p>

            <p><b>{% translate "Data Input" %}</b>: {{ members_di_size }}</p>

		</div>

		<div class="col s12 m6">
			<h4>{% translate "Data" %}</h4>

			<p><b>{% translate "Dataset Size" %}</b>: {{ data_size }} </p>

            <p><b>{% translate "Last Updated" %}</b>: {{ data_last_updated }}</p>
		</div>
	</div>

{% endblock content %}

units/templates/units/edit.html
{% extends "base/base.html" %}

{% load i18n materializecss %}

{% block content %}
	<h2>{% trans "Editing Unit" %}</h2>

	<div class="row">
		<div class="col">
			<form action="" method="post">
				{% csrf_token %}

				{{ form|materializecss }}

				<p class="center">
					<button class="btn waves-effect waves-light blue darken-3" type="submit" name="action">{% trans "Submit" %}
			    	<i class="material-icons right">send</i>
			  		</button>
				</p>
			</form>
		</div>
	</div>
{% endblock content %}

units/templates/units/list.html
{% extends "base/base.html" %}
{% load i18n data_tags %}

{% block content %}
	<h1>{% translate "Units" %}</h1>

	<table class="table">

        <thead>
          <tr>
           	<th class="s2">
           		id
            </th>
            <th>
           		{% translate "Name" %}
            </th>
            <th>
           		{% translate "# Data" %}
            </th>
            <th>
           		{% translate "Last Updated" %}
            </th>
          </tr>
        </thead>

        <tbody>
          {% for unit in units %}
          <tr>
          	<td><a href="{% url "units:detail" unit.pk%}">{{ unit.id }}</a></td>
          	<td><a href="{% url "units:detail" unit.pk%}">{{ unit.name }}</a></td>
          	<td>{{ unit.data_amount }}</td>
          	<td>{{ unit.last_updated }}</td>
          </tr>
          {% endfor %}
        </tbody>

    </table>

    {% include "base/includes/paginator.html" with page_obj=units view="units:list" %}

{% endblock content %}

units/templates/units/users_detail.html
{% extends "base/base.html" %}

{% load i18n %}

{% block content %}
	<h2>
		<i class="material-icons circle text-darken-4 orange-text icon-primary">person</i>
		{{ user.name }} ({{user.username}})
	</h2>
	{% if user.email %}
	<h4 class="cellphone-number blue-grey-text text-darken-2 indent-small">
    	<i class="material-icons prefix valign-bottom" >email</i>
    	{{ user.email }}
    </h4>
    {% endif %}
	{% if user.cellphone %}
	<h4 class="cellphone-number blue-grey-text text-darken-2 indent-small">
    	<i class="material-icons prefix" style="vertical-align: bottom;">phone</i>
    	{{ user.cellphone }}
    </h4>
    {% endif %}

    {% if request.user.user_type == request.user.MANAGER or request.user == user %}
    <div class="fixed-action-btn">
	  <a class="btn-floating btn-large red">
	    <i class="large material-icons">more_horiz</i>
	  </a>
	  <ul>
	    <li><a href="{% url 'units:current:users-edit' user.pk %}" class="btn-floating blue darken-1">
	    	<i class="material-icons">mode_edit</i></a>
	    </li>
	  </ul>
	</div>

	<h4>{{ user.get_user_type_display }}</h4>
    <p>
    	{% if not user.password %}
    	<blockquote>
    		{% trans "USER WITHOUT PASSWORD" %}
    	</blockquote>
    	{% endif %}
    	<a class="btn btn-large red {% if user.password %}lighten-2{% else %}darken-2{% endif %}" href="{% url 'units:current:users-set-password' user.pk %}">{% trans "Set Password" %}</a>
    </p>
    {% endif %}

{% endblock content %}

{% block extra_js %}
	<script>
	  document.addEventListener('DOMContentLoaded', function() {
	    var elems = document.querySelectorAll('.fixed-action-btn');
	    var instances = M.FloatingActionButton.init(elems, {
	      direction: 'left'
	    });
	  });

	</script>
{% endblock extra_js %}

units/templates/units/users_edit.html
{% extends "base/base.html" %}

{% load i18n materializecss %}

{% block content %}
	<h2>{% trans "Editing User" %}</h2>

	<div class="row">
		<div class="col">
			<form action="" method="post">
				{% csrf_token %}

				{{ form|materializecss }}

				{% include "base/includes/submit_button.html" %}
			</form>
		</div>
	</div>
{% endblock content %}

units/templates/units/users_list.html
{% extends "base/base.html" %}

{% load i18n %}

{% block content %}
	<h2>{% trans "Unit's Members" %}</h2>
	{% if users %}
		<ul class="collection">
			{% for user in users %}
			<li class="collection-item avatar">
				<a href="{{ user.url }}">
      		<i class="material-icons circle deep-orange darken-4">person</i>
        </a>
      		<span class="title">
            <a href="{{ user.url }}">{{ user.name|upper }}</a>
          </span>
      		{% if user.cellphone or user.email %}
      		<p>{{ user.username }} {% if user.email %}| {{ user.email }}{% endif %} {% if user.cellphone %}- {{ user.cellphone }}{% endif %}</p>
      		{% endif %}
      		<span class="right secondary-content">{{ user.get_user_type_display }}</span>
    		</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>{% trans "No users available yet" %}</p>
	{% endif %}

  {% if request.user.user_type == request.user.MANAGER %}
  <div class="row">
      <div class="col s12 center">
          <a href="{% url 'units:current:users-new' %}"
             class="btn btn-large red">
              <i class="material-icons left">person_add</i>
              {% trans "New User" %}
          </a>
      </div>
  </div>
  {% endif %}
{% endblock content %}

units/templates/units/users_new.html
{% extends "base/base.html" %}

{% load i18n materializecss %}

{% block content %}
	<h2>{% trans "New Unit User" %}</h2>

	<div class="row">
		<div class="col">
			<form action="" method="post">
				{% csrf_token %}
				{{ form|materializecss }}

				<p class="center">
					<button class="btn waves-effect waves-light blue darken-3" type="submit" name="action">{% trans "Submit" %}
			    	<i class="material-icons right">send</i>
			  		</button>
				</p>
			</form>
		</div>
	</div>
{% endblock content %}

units/templates/units/users_set_password.html
{% extends "base/base.html" %}

{% load i18n materializecss %}

{% block content %}
	<h2>{% trans "Set password for" %} {{ user.name }}</h2>

	<form action="" method="post">
		{% csrf_token %}
		{{ form|materializecss }}

		<p class="center">
			<button class="btn waves-effect waves-light blue darken-3" type="submit" name="action">{% trans "Submit" %}
	    	<i class="material-icons right">send</i>
	  		</button>
		</p>
	</form>
{% endblock content %}